Single node replica set
akkadotnet/Akka.Persistence.MongoDB pull request #300
Opened 2023-02-23 13:45 UTC by eaba

2023-02-23 14:16 UTC, Aaronontheweb commented on src/Akka.Persistence.MongoDb/MongoDbSettings.cs
> +        public string DatabaseName { get; private set; } = "akka";
Why is this needed?

2023-02-23 14:20 UTC, Aaronontheweb commented on src/Akka.Persistence.MongoDb.Tests/Bug61FixSpec.cs
> -        private static Config CreateSpecConfig(DatabaseFixture databaseFixture, int id)
so you actually need this Id if the tests are being run in parallel - otherwise you'll get cross-contamination.

2023-02-23 14:21 UTC, Aaronontheweb commented on src/Akka.Persistence.MongoDb.Tests/Bug61FixSpec.cs
> -        private static Config CreateSpecConfig(DatabaseFixture databaseFixture, int id)
There has to be a way to segregate tests, each onto their own database.

2023-02-23 14:25 UTC, eaba commented on src/Akka.Persistence.MongoDb/MongoDbSettings.cs
> +        public string DatabaseName { get; private set; } = "akka";
`_connectionString.DatabaseName` is not there

2023-02-23 16:39 UTC, Aaronontheweb commented on src/Akka.Persistence.MongoDb/Akka.Persistence.MongoDb.csproj
> +    <PackageReference Include="MongoDB.Driver" Version="2.19.0" />
Skip the upgrade for now. One thing at a time.

2023-02-25 20:33 UTC, Aaronontheweb commented
looks good @eaba - I'll check it out

2023-02-26 23:15 UTC, Aaronontheweb requested changes
Overall, looks good to me but needs cleanup @eaba

2023-02-26 23:15 UTC, Aaronontheweb commented on src/Akka.Persistence.MongoDb/Journal/MongoDbJournal.cs
> +        public static readonly AtomicCounter Counter = new AtomicCounter(0);
Need to be removed

2023-02-26 23:15 UTC, Aaronontheweb commented on src/Akka.Persistence.MongoDb.Tests/DatabaseFixture.cs
> +            var s = _runner.ConnectionString.Split('?');
Can you add a comment explaining what this is for?

2023-02-26 23:15 UTC, Aaronontheweb commented on src/Akka.Persistence.MongoDb.Tests/MongoDbAllEventsSpec.cs
> +            var s = databaseFixture.ConnectionString.Split('?');
Is there a way we could standardize this into a function, so we don't have to do this string manipulation the same way in ~12 different tests?

2023-02-26 23:15 UTC, Aaronontheweb commented on src/Akka.Persistence.MongoDb/Journal/MongoDbJournal.cs
> +        public static readonly AtomicCounter Counter = new AtomicCounter(0);
Don't put testing infrastructure onto the journal itself, and definitely not in the public API. A separate `static class` with the `Counter` property inside the test suite is a more suitable location.

2023-02-27 15:09 UTC, Aaronontheweb requested changes
Looks better, but still needs some cleanup

2023-02-27 15:09 UTC, Aaronontheweb commented on src/Akka.Persistence.MongoDb.Tests/Bug25FixSpec.cs
> +        private static MongoDbConnectionString _mongoDb = new MongoDbConnectionString();
Should not be `static` - needs to be instanced so there can't be cross-pollination between tests in the same fixture. Same goes for every unit test fixture.

2023-02-27 15:09 UTC, Aaronontheweb commented on src/Akka.Persistence.MongoDb.Tests/Bug25FixSpec.cs
> +        private static MongoDbConnectionString _mongoDb = new MongoDbConnectionString();
Why can't this value just be passed in from the fixture?

2023-02-27 17:19 UTC, Aaronontheweb approved these changes
LGTM

2023-02-27 17:30 UTC, merged